# Generated by Django 5.1.4 on 2025-02-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sneder',
            new_name='sender',
        ),
    ]
